version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chat
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
